
<Program> ::= <ToplevelList>;

<ToplevelList> ::= 
    <TopLevel> <ToplevelList> | 
    <TopLevel>;

<TopLevel> ::= <FuncDecl>;

<FuncDecl> ::= "fn" <IDENTIFIER> "(" <ParamList> ")" ":" <Type> "=" <Block> ";";

<Block> ::= "{" (StatementList | Empty) "}";

<StatementList> ::= 
    <Statement> <StatementList> | 
    <Statement>;

<Statement> ::=
    <Declaration>     |
    <Assignment>      |
    <IfStatement>     |
    <WhileStatement>  |
    <BreakStatement>  |
    <ReturnStatement> |
    <PrintStatement>;

<Declaration> ::= "let" "IDENTIFIER": <Type> "=" <Expression> ";";

<Type> ::= ("int" | "bool");

<Assignment> ::= "IDENTIFIER" "=" <Expression> ";";

<Expression> ::=
    <Equality> ("and" | "or") <Equality> |
    <Equality>;

<Equality> ::=
    <Comparison> "==" <Comparison> |
    <Comparison>; 

<Comparison> ::= 
    <Sum> ("<" | "<=" | "==" | ">=" | ">" | "!=") <Sum> |
    <Sum>;

<Sum> ::=
    <Product> ("+" | "-") <Sum> |
    <Product>;

<Product> ::=
    <Factor> ("*" | "/" | "%") <Product> |
    <Factor>;

<Factor> ::=
    <Call>               |
    ("-" | "!") <Factor> |
    "IDENTIFIER"         |
    "LITERAL"            |
    "(" <Expression> ")";

<Call> ::= "IDENTIFIER" "(" <ArgList> ")";

<ParamList> ::=
    <Param>  "," <ParamList> |
    <Param>;

<Param> ::= "IDENTIFIER" ":" <Type>;

<ArgList> ::=
    <Expression> "," <ArgList> |
    <Expression>;

<IfStatement> ::=
    "if" <Expression> <Block> |
    "if" <Expression> <Block> "else" <Block>;

<WhileStatement> ::= "while" <Expression> <Block>;

<ReturnStatement> ::= "return" <Expression> ";";

<BreakStatement> ::= "break" ";"

<PrintStatement> ::= "print" <Expression> ";"
